// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfwFhYinmpmfoffnkGD5y8-fCotoT4Bdk',
    appId: '1:364111693833:web:61ea7b0845e3276c5090d8',
    messagingSenderId: '364111693833',
    projectId: 'first-note-project',
    authDomain: 'first-note-project.firebaseapp.com',
    storageBucket: 'first-note-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh4uhRuc3PWSQjmTkzhtymS3pBVFR3OPM',
    appId: '1:364111693833:android:a686583e5cfa69805090d8',
    messagingSenderId: '364111693833',
    projectId: 'first-note-project',
    storageBucket: 'first-note-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4RleWUiz2LJMnX2xszaDi6pd3lAROgts',
    appId: '1:364111693833:ios:59cabf3586d803bb5090d8',
    messagingSenderId: '364111693833',
    projectId: 'first-note-project',
    storageBucket: 'first-note-project.appspot.com',
    iosClientId:
        '364111693833-kl6seeaj0109o2ijj324ht3cs4du31q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4RleWUiz2LJMnX2xszaDi6pd3lAROgts',
    appId: '1:364111693833:ios:59cabf3586d803bb5090d8',
    messagingSenderId: '364111693833',
    projectId: 'first-note-project',
    storageBucket: 'first-note-project.appspot.com',
    iosClientId:
        '364111693833-kl6seeaj0109o2ijj324ht3cs4du31q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
